<a href="https://colab.research.google.com/github/JaviLaura/ML_multivariate_lin_regression/blob/main/ML_multivariate_lin_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
from sklearn import linear_model
!pip install word2number
from word2number import w2n

  Preparing metadata (setup.py) ... done
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5568 sha256=0691766b1b58b2e946226638a5ccfe34904cd21390136f9fb08b6ba9dd03dce4
  Stored in directory: /root/.cache/pip/wheels/84/ff/26/d3cfbd971e96c5aa3737ecfced81628830d7359b55fbb8ca3b
Successfully built word2number


In [2]:
from google.colab import files

uploaded = files.upload()

Saving hiring.csv to hiring.csv


Import csv

In [3]:
df = pd.read_csv('hiring.csv')
display(df)

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

Fill null values in 'experience' column with zero assuming that no value entered means zero.

In [6]:
df.experience = df.experience.fillna(0)
display(df)

experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

Convert 'experience' column values to numbers.

In [7]:
df['experience'] = df['experience'].apply(lambda x: w2n.word_to_num(str(x)))
display(df)

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

Fill null values in 'test_score' column with median.

In [9]:
import math
median_test_score = math.floor(df.test_score.median())
median_test_score

8

In [10]:
df.test_score = df.test_score.fillna(median_test_score)
display(df)

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         8.0                7   72000
7          11         7.0                8   80000

Formula:

y = m1x1 + m2x2 + m3x3 + b

m1, m2, and m3 are 'coefficents

b is 'intercept'

'Dependent variable' is salary.

'Features' or 'independent variables' are experience, test_score, and interview_score.

In [11]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience', 'test_score', 'interview_score']],df.salary)

LinearRegression()

Look at coefficients

In [12]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

Look at intercept

In [13]:
reg.intercept_

17737.263464337688

Predict salary for someone with 2 years experience, 9 for test score, and 6 for interview score

In [14]:
reg.predict([[2, 9, 6]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([53205.96797671])

Formula to double check above prediction:

In [15]:
# price = m1 * experience + m2 * test_score + m3 * interview_score + b
2812.95487627 * 2 + 1845.70596798 * 9 + 2205.24017467 * 6 + 17737.263464337688

53205.96797671769

Predict salary for someone with 12 years experience, 10 for test score, and 10 for interview score

In [16]:
reg.predict([[12, 10, 10]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([92002.18340611])

Formula to double check above prediction:

In [17]:
# price = m1 * experience + m2 * test_score + m3 * interview_score + b
2812.95487627 * 12 + 1845.70596798 * 10 + 2205.24017467 * 10 + 17737.263464337688

92002.18340607767